name: Add New Digital Nomad Group
description: Submit a new group to be added to the directory
title: "[NEW GROUP]: "
labels: ["New Group"]
assignees:
  - REPO_OWNER

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for contributing to the Digital Nomad Communities Directory!
        Please fill out this form to add a new group to our directory.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform is this group hosted on?
      options:
        - WhatsApp
        - Telegram
        - Discord
        - Facebook
        - WeChat
        - Slack
        - Linktree
        - Meetup
        - Other (please specify in the description)
      default: 0
    validations:
      required: true

  - type: input
    id: group_name
    attributes:
      label: Group Name
      description: The name of the digital nomad group
      placeholder: "e.g. Digital Nomads Barcelona"
    validations:
      required: true

  - type: input
    id: group_url
    attributes:
      label: Group URL
      description: The direct link to join the group
      placeholder: "https://chat.whatsapp.com/..."
    validations:
      required: true

  - type: dropdown
    id: continent
    attributes:
      label: Continent
      description: Which continent is this group primarily based in? Empty for global/continent-wide groups. NOTE Multiple places are allowed, but not using this form.
      options:
        - Africa
        - Asia
        - Australia
        - Europe
        - North America
        - South America
        - Central America
        - Oceania
        - Antarctica
    validations:
      required: false

  - type: input
    id: country
    attributes:
      label: Country
      description: Which country is this group primarily based in? (Leave blank for global/continent-wide groups)
      placeholder: "e.g. Spain"
    validations:
      required: false

  - type: input
    id: city
    attributes:
      label: City
      description: Which city is this group primarily based in? (Leave blank for country-wide groups)
      placeholder: "e.g. Barcelona"
    validations:
      required: false

  - type: input
    id: region
    attributes:
      label: Region
      description: Which region is this group primarily based in? (Optional)
      placeholder: "e.g. Patagonia"
    validations:
      required: false

  - type: checkboxes
    id: commercial
    attributes:
      label: Commercial Group
      description: Is this a commercial/paid group?
      options:
        - label: This is a commercial or paid group
    validations:
      required: false

  - type: input
    id: language_id
    attributes:
      label: Primary Language if not English
      description: Two-letter language code (ISO 639-1) for the group's primary language. See the list at https://localizely.com/iso-639-1-list/
      placeholder: "e.g. es, fr"
    validations:
      required: false

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated tags for easier searching (e.g., coworking, events, housing)
      placeholder: "e.g. coworking, events, language-exchange"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief description of the group (optional)
      placeholder: "A community for digital nomads in Barcelona to share resources and organize meetups."
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: This is an active group specifically for digital nomads or travelers
          required: true
        - label: I have permission to share this group or it's publicly available
          required: true
