name: Add New Digital Nomad Group
description: Submit a new group to be added to the directory
title: "[NEW GROUP]: "
labels: ["new-group"]
assignees:
  - REPO_OWNER

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for contributing to the Digital Nomad Communities Directory!
        Please fill out this form to add a new group to our directory.
        
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform is this group hosted on?
      options:
        - WhatsApp
        - Telegram
        - Discord
        - Facebook
        - WeChat
        - Slack
        - Meetup
        - Other (please specify in the description)
      default: 0
    validations:
      required: true
      
  - type: input
    id: group_name
    attributes:
      label: Group Name
      description: The name of the digital nomad group
      placeholder: "e.g., Digital Nomads Barcelona"
    validations:
      required: true
      
  - type: input
    id: group_url
    attributes:
      label: Group URL
      description: The direct link to join the group
      placeholder: "https://chat.whatsapp.com/..."
    validations:
      required: true
      
  - type: dropdown
    id: continent
    attributes:
      label: Continent
      description: Which continent is this group primarily based in?
      options:
        - World (for global groups)
        - Africa
        - Asia
        - Australia
        - Europe
        - North America
        - South America
        - Central America
        - Antarctica
    validations:
      required: true
      
  - type: input
    id: country
    attributes:
      label: Country
      description: Which country is this group primarily based in? (Leave blank for global/continent-wide groups)
      placeholder: "e.g., Spain"
      
  - type: input
    id: city
    attributes:
      label: City
      description: Which city is this group primarily based in? (Leave blank for country-wide groups)
      placeholder: "e.g., Barcelona"
      
  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated tags for easier searching (e.g., coworking, events, housing)
      placeholder: "e.g., coworking, events, language-exchange"
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief description of the group (optional)
      placeholder: "A community for digital nomads in Barcelona to share resources and organize meetups."
      
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: This is an active group specifically for digital nomads or travelers
          required: true
        - label: I have verified that this group is not already in the directory
          required: true
        - label: I have permission to share this group or it's publicly available
          required: true
