name: Process New Group Submission

on:
  issues:
    types: [opened, edited]

jobs:
  process-submission:
    if: contains(github.event.issue.labels.*.name, 'New Group')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests PyGithub iso3166

      - name: Process Issue Form
        id: process
        run: |
          python .github/scripts/process_group_submission.py \
            --issue-body "${{ toJSON(github.event.issue.body) }}" \
            --issue-number "${{ github.event.issue.number }}" \
            --github-output $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: steps.process.outputs.valid == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add new group from issue #${{ github.event.issue.number }}: ${{ steps.process.outputs.group_name }}"
          branch: add-group-issue-${{ github.event.issue.number }}
          delete-branch: true
          title: "Add new group: ${{ steps.process.outputs.group_name }}"
          labels: |
            New Group
          body: |
            This PR adds a new group from issue #${{ github.event.issue.number }}

            **Group Name:** ${{ steps.process.outputs.group_name }}
            **Platform:** ${{ steps.process.outputs.platform }}
            **Location:** ${{ steps.process.outputs.location }}

            Automated PR created by the group submission workflow.

      - name: Comment on Issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for your submission!

            ${{ steps.process.outputs.message }}

            ${{ steps.process.outputs.valid == 'true' && format('Your group has been added to the directory. A pull request has been created: %s', steps.create-pr.outputs.pull-request-url) || 'Please fix the issues above and we will process your submission.' }}
