name: Validate YAML

on:
  pull_request:
    paths:
      - "directory.yaml" # Trigger only when directory.yaml is modified

jobs:
  validate-yaml:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code, including the PR changes
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Use the latest Python 3.x version

      # Install pykwalify
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pykwalify

      # Run the validation script
      - name: Validate directory.yaml against schema.yaml
        run: |
          python .github/scripts/validate_yaml.py directory.yaml schema.yaml
