name: Validate YAML Directory

on:
  pull_request:
    branches: [main]
    paths:
      - "directory.yaml"
      - ".github/scripts/validate_yaml.py"

jobs:
  validate:
    name: Validate YAML
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml pykwalify

      - name: Create Check Run
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: YAML Validation
          status: in_progress

      - name: Validate directory.yaml
        id: validate
        continue-on-error: true
        run: |
          output=$(python .github/scripts/validate_yaml.py 2>&1)
          echo "::set-output name=output::$output"
          if [ $? -eq 0 ]; then
            echo "::set-output name=status::success"
          else
            echo "::set-output name=status::failure"
          fi

      - name: Update Check Run
        uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: YAML Validation
          status: completed
          conclusion: ${{ steps.validate.outputs.status }}
          output: |
            {"summary": "${{ steps.validate.outputs.output }}"}
