name: Validate YAML Directory

on:
  push:
    branches: [main]
    paths:
      - "directory.yaml"
  pull_request:
    branches: [main]
    paths:
      - "directory.yaml"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jsonschema iso3166 pycountry

      - name: Validate directory.yaml
        run: python .github/scripts/validate_yaml.py
